### PR TITLE
Preformance enhamcement to TwoSymbol Calculations

### PR DESCRIPTION
**Pull request by hsizek**
Two modifications:
1. Q_history performance modification, to make searching more efficient
2. Reordering TS expansion method to decrease duplicate calculations, making calculation more efficient.

### CODE REVIEW

**Comment by hsizek** [comment]
@rionbr I don't know how GitHub's interface really works, so here is another modification that goes on top of the previous fork (#13 ). This modifies the same logic and has more details in the individual commits.

**Comment by rionbr** [comment]
Hey @hsizek no problem, It also took me a while and I don't think I've fully mastered it yet :-) But I guess you can think of PR like a separate branch, where you can continue to push commits to it. When everybody is satisfied, the branch is merged to the master and the PR is closed.

**Comment by rionbr** [comment]
I haven't forgot about this PR @hsizek. We are trying to finish the Effective Connectivity paper (on another branch) and then I will work on this, ok? Cheers!

**Comment by rionbr** [comment]
Now that v0.1 is released we need to incorporate this @hsizek enhancement. A refactoring/cleaning of the TwoSymbol methods is probably in order. 👍

**Pull request closed without merging**
